repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        exclude: |
            (?x)(
                ^toolkits/grscenes_scripts/README.md|
                ^toolkits/indoor_scenes_generation/infinigen/infinigen_examples/constraints
            )
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '^(.*/lcmtypes/.*)'
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
        exclude: '^(.*/lcmtypes/.*)'
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key
      - id: check-json
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: ["--number", "--table-width", "200"]
        additional_dependencies:
            - mdformat-openmmlab
            - mdformat_frontmatter
            - linkify-it-py
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.27
    hooks:
      - id: pymarkdown
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
        entry: "gitleaks dir"
        args: [
          "--verbose",
          "--redact=50"
        ]
  - repo: https://github.com/PyCQA/pylint/
    rev: v2.17.2
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: false
        args:
            [   '--jobs=4',
                '--disable=all',
                '--enable=E,F'
            ]
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        args: [-q,-c, .github/md-link-config.json]
