name: Run linters using pre-commit

on:
  pull_request:
    branches: [main]
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pre-commit
      run : |
        pip install pre-commit==3.4.0
        pre-commit install
        pre-commit run --all-files
