name: Run linters using pre-commit

on:
  pull_request:
    branches: [main]
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: pre-commit
      run : |
        python --version
        pip install pre-commit==3.4.0
        pre-commit install
        pre-commit clean
        pre-commit run --all-files
